'use client';

import { useAuth } from '@/lib/auth';
import { useApiSwr } from '@/lib/useApiSwr';

export default function InvoicesPage() {
  const { user } = useAuth();
  const { data: billing } = useApiSwr<any>(user?.companyId ? `/corporate/companies/${user.companyId}/billing-summary` : null);

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-xl font-semibold">Billing &amp; invoices</h1>
        <p className="text-sm text-slate-500">Invoices are generated by the platform per billing period from your company's completed trips.</p>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        <div className="card"><div className="text-sm text-slate-500">Credit limit</div><div className="mt-1 text-2xl font-semibold">₹{billing?.creditLimit ?? '—'}</div></div>
        <div className="card"><div className="text-sm text-slate-500">Credit used</div><div className="mt-1 text-2xl font-semibold">₹{billing?.creditUsed ?? '—'}</div></div>
        <div className="card"><div className="text-sm text-slate-500">Credit available</div><div className="mt-1 text-2xl font-semibold">₹{billing?.creditAvailable ?? '—'}</div></div>
      </div>

      <div className="card overflow-x-auto">
        <table className="data-table">
          <thead><tr><th>Invoice #</th><th>Period</th><th>Total</th><th>Paid</th><th>Status</th></tr></thead>
          <tbody>
            {(billing?.invoices ?? []).map((inv: any) => (
              <tr key={inv.id}>
                <td>{inv.invoiceNumber}</td>
                <td>{new Date(inv.periodStart).toLocaleDateString()} – {new Date(inv.periodEnd).toLocaleDateString()}</td>
                <td>₹{inv.totalAmount}</td>
                <td>₹{inv.amountPaid}</td>
                <td>{inv.status}</td>
              </tr>
            ))}
            {(billing?.invoices ?? []).length === 0 && (
              <tr><td colSpan={5} className="py-6 text-center text-slate-400">No invoices issued yet.</td></tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
